-- Tabla institucional EID adaptada desde el respaldo MariaDB para uso en Supabase/PostgreSQL.
-- Base de origen: supabase/EID.sql

create table if not exists public.eid (
  id bigint generated by default as identity primary key,
  dimension varchar(150) not null,
  sub_dimension varchar(255) not null,
  numero_estandar varchar(20) not null,
  descripcion_estandar text not null
);

create unique index if not exists eid_numero_estandar_key on public.eid (numero_estandar);
create index if not exists eid_dimension_idx on public.eid (dimension);
create index if not exists eid_sub_dimension_idx on public.eid (sub_dimension);

insert into public.eid (id, dimension, sub_dimension, numero_estandar, descripcion_estandar)
values
  (1, 'Liderazgo', 'Liderazgo del sostenedor', '1.1', 'El sostenedor se responsabiliza por el desarrollo del Proyecto Educativo Institucional, el desempeño y el cumplimiento de la normativa vigente de los establecimientos a su cargo.'),
  (2, 'Liderazgo', 'Liderazgo del sostenedor', '1.2', 'El sostenedor define formalmente las funciones que asumira centralizadamente y aquellas que delegara a los equipos directivos de los establecimientos a su cargo, y cumple con sus compromisos.'),
  (3, 'Liderazgo', 'Liderazgo del sostenedor', '1.3', 'El sostenedor comunica altas expectativas a los directores de los establecimientos a su cargo, les establece metas desafiantes, clarifica sus atribuciones y evalua su desempeno.'),
  (4, 'Liderazgo', 'Liderazgo del sostenedor', '1.4', 'El sostenedor introduce, de manera oportuna, los cambios estructurales necesarios para asegurar la viabilidad y buen funcionamiento de los establecimientos a su cargo.'),
  (5, 'Liderazgo', 'Liderazgo del sostenedor', '1.5', 'El sostenedor genera canales fluidos de comunicacion con los directores y las comunidades educativas de los establecimientos a su cargo, y con las instituciones del Estado pertinentes.'),
  (6, 'Liderazgo', 'Liderazgo del sostenedor', '1.6', 'El sostenedor se asegura de que los establecimientos a su cargo funcionen en red, y en el caso de tener solo un centro educativo bajo su responsabilidad, procura establecer alianzas con establecimientos similares.'),
  (7, 'Liderazgo', 'Liderazgo del director', '2.1', 'El director centra su gestion en el logro de los objetivos academicos y formativos del establecimiento, y se responsabiliza por sus resultados.'),
  (8, 'Liderazgo', 'Liderazgo del director', '2.2', 'El director conduce de manera efectiva el funcionamiento general del establecimiento.'),
  (9, 'Liderazgo', 'Liderazgo del director', '2.3', 'El director instaura una cultura de altas expectativas y moviliza a la comunidad educativa hacia la mejora continua.'),
  (10, 'Liderazgo', 'Liderazgo del director', '2.4', 'El director instaura en el personal una cultura de compromiso y colaboracion con la tarea educativa.'),
  (11, 'Liderazgo', 'Liderazgo del director', '2.5', 'El director instaura un ambiente cultural y academicamente estimulante.'),
  (12, 'Liderazgo', 'Planificacion y gestion de resultados', '3.1', 'El director elabora un plan de mejoramiento de acuerdo con el Proyecto Educativo Institucional.'),
  (13, 'Liderazgo', 'Planificacion y gestion de resultados', '3.2', 'El director monitorea la implementacion del plan de mejoramiento, evalua el cumplimiento de las metas y realiza adecuaciones cuando corresponde.'),
  (14, 'Liderazgo', 'Planificacion y gestion de resultados', '3.3', 'El director y el equipo directivo sistematizan continuamente los datos relevantes de la gestion escolar y los utilizan para tomar decisiones.'),
  (15, 'Gestion pedagogica', 'Gestion curricular', '4.1', 'El director y el equipo tecnico-pedagogico coordinan la implementacion efectiva de las Bases Curriculares y los programas de estudio'),
  (16, 'Gestion pedagogica', 'Gestion curricular', '4.2', 'El director y el equipo tecnico-pedagogico acuerdan con los docentes lineamientos pedagogicos comunes para la implementacion efectiva del curriculum.'),
  (17, 'Gestion pedagogica', 'Gestion curricular', '4.3', 'El equipo directivo gestiona la elaboracion de planificaciones que contribuyen a la conduccion efectiva de los procesos de ensenanza-aprendizaje.'),
  (18, 'Gestion pedagogica', 'Gestion curricular', '4.4', 'El equipo directivo y el tecnico-pedagogico acompanan a los docentes mediante la observacion y retroalimentacion de clases.'),
  (19, 'Gestion pedagogica', 'Gestion curricular', '4.5', 'El director y el equipo tecnico-pedagogico coordinan un proceso efectivo de evaluacion y monitoreo de los aprendizajes para la toma de decisiones pedagogicas.'),
  (20, 'Gestion pedagogica', 'Ensenanza y aprendizaje en el aula', '5.1', 'Los docentes centran sus clases en los Objetivos de Aprendizaje estipulados en las Bases Curriculares, con un manejo riguroso de las habilidades, contenidos y actitudes a desarrollar.'),
  (21, 'Gestion pedagogica', 'Ensenanza y aprendizaje en el aula', '5.2', 'Los docentes usan estrategias efectivas de ensenanza-aprendizaje para el logro de los Objetivos de Aprendizaje.'),
  (22, 'Gestion pedagogica', 'Ensenanza y aprendizaje en el aula', '5.3', 'Los docentes establecen vinculos pedagogicos positivos con todos sus estudiantes y generan motivacion por la asignatura.'),
  (23, 'Gestion pedagogica', 'Ensenanza y aprendizaje en el aula', '5.4', 'Los docentes monitorean el aprendizaje de sus estudiantes y les entregan retroalimentacion constante durante las clases.'),
  (24, 'Gestion pedagogica', 'Ensenanza y aprendizaje en el aula', '5.5', 'Los docentes se aseguran de que todos sus estudiantes trabajen en clases y promueven el estudio independiente y la responsabilidad.'),
  (25, 'Gestion pedagogica', 'Ensenanza y aprendizaje en el aula', '5.6', 'Los docentes hacen uso efectivo del tiempo de clases para que este se destine al proceso de ensenanza-aprendizaje.'),
  (26, 'Gestion pedagogica', 'Apoyo al desarrollo de los estudiantes', '6.1', 'El equipo tecnico-pedagogico y los docentes identifican tempranamente a los estudiantes que presentan vacios de aprendizaje o necesidades educativas especiales, y articulan los apoyos necesarios.'),
  (27, 'Gestion pedagogica', 'Apoyo al desarrollo de los estudiantes', '6.2', 'El equipo directivo, en conjunto con los docentes, implementan estrategias efectivas para potenciar a los estudiantes con intereses diversos y habilidades destacadas.'),
  (28, 'Gestion pedagogica', 'Apoyo al desarrollo de los estudiantes', '6.3', 'El equipo directivo y los docentes identifican a tiempo a los estudiantes que presentan dificultades sociales, afectivas y conductuales, e implementan medidas efectivas para apoyarlos.'),
  (29, 'Gestion pedagogica', 'Apoyo al desarrollo de los estudiantes', '6.4', 'El equipo directivo y los docentes implementan estrategias efectivas para evitar la desercion escolar.'),
  (30, 'Gestion pedagogica', 'Apoyo al desarrollo de los estudiantes', '6.5', 'El equipo directivo y el tecnico-pedagogico incorporan un enfoque inclusivo e intercultural para asegurar el desarrollo de los estudiantes de distintas culturas.'),
  (31, 'Gestion de la convivencia', 'Formacion', '7.1', 'El equipo directivo planifica, implementa y monitorea programas e iniciativas para la formacion integral de sus estudiantes de acuerdo con el Proyecto Educativo Institucional.'),
  (32, 'Gestion de la convivencia', 'Formacion', '7.2', 'El profesor jefe acompana activamente a los estudiantes de su curso y los orienta formativa y academicamente.'),
  (33, 'Gestion de la convivencia', 'Formacion', '7.3', 'El equipo directivo y los docentes transmiten altas expectativas a los estudiantes, y los orientan y apoyan en la toma de decisiones sobre su futuro.'),
  (34, 'Gestion de la convivencia', 'Formacion', '7.4', 'El equipo directivo y los docentes promueven habitos de vida saludable y conductas de autocuidado entre los estudiantes.'),
  (35, 'Gestion de la convivencia', 'Formacion', '7.5', 'El equipo directivo y los profesores jefe promueven de manera activa que las familias y los apoderados se involucren y participen en el proceso educativo de los estudiantes.'),
  (36, 'Gestion de la convivencia', 'Convivencia', '8.1', 'El equipo directivo y los docentes promueven, modelan y aseguran un ambiente de amabilidad y respeto entre todos los miembros de la comunidad educativa'),
  (37, 'Gestion de la convivencia', 'Convivencia', '8.2', 'El equipo directivo y los docentes valoran y promueven la diversidad, incluyendo la equidad de genero, como parte de la riqueza de los grupos humanos, y previenen cualquier tipo de discriminacion.'),
  (38, 'Gestion de la convivencia', 'Convivencia', '8.3', 'El equipo directivo difunde y exige el cumplimiento del Reglamento de Convivencia, que explicita las normas para organizar la vida en comun.'),
  (39, 'Gestion de la convivencia', 'Convivencia', '8.4', 'El equipo directivo y los docentes acuerdan reglas y procedimientos para facilitar el desarrollo de las actividades pedagogicas.'),
  (40, 'Gestion de la convivencia', 'Convivencia', '8.5', 'El personal del establecimiento resguarda la integridad fisica y psicologica de todos los estudiantes durante la jornada escolar.'),
  (41, 'Gestion de la convivencia', 'Convivencia', '8.6', 'El equipo directivo y los docentes abordan decididamente las conductas que atentan contra la sana convivencia dentro del establecimiento'),
  (42, 'Gestion de la convivencia', 'Participacion y vida democratica', '9.1', 'El equipo directivo y los docentes promueven el sentido de pertenencia y participacion en torno al Proyecto Educativo Institucional.'),
  (43, 'Gestion de la convivencia', 'Participacion y vida democratica', '9.2', 'El personal del establecimiento promueve entre los estudiantes un sentido de responsabilidad con la sociedad y el medio ambiente, y los motivan a realizar aportes concretos.'),
  (44, 'Gestion de la convivencia', 'Participacion y vida democratica', '9.3', 'El equipo directivo y los docentes fomentan entre los estudiantes la expresion de opiniones, la deliberacion y el debate fundamentado de ideas.'),
  (45, 'Gestion de la convivencia', 'Participacion y vida democratica', '9.4', 'El equipo directivo promueve la formacion democratica y ciudadana, y la participacion activa de los estudiantes mediante el apoyo al Centro de Alumnos y a las directivas de curso.'),
  (46, 'Gestion de la convivencia', 'Participacion y vida democratica', '9.5', 'El equipo directivo promueve la participacion activa de los distintos estamentos de la comunidad educativa para apoyar el desarrollo del Proyecto Educativo Institucional.'),
  (47, 'Gestion de recursos', 'Gestion de personal', '10.1', 'El sostenedor o el equipo directivo organiza y maneja de manera efectiva los aspectos administrativos del personal.'),
  (48, 'Gestion de recursos', 'Gestion de personal', '10.2', 'El sostenedor o el equipo directivo implementa estrategias efectivas para contar con personal idoneo y competente.'),
  (49, 'Gestion de recursos', 'Gestion de personal', '10.3', 'El equipo directivo implementa un sistema de evaluacion y retroalimentacion del desempeno del personal.'),
  (50, 'Gestion de recursos', 'Gestion de personal', '10.4', 'El sostenedor o el equipo directivo gestiona el desarrollo profesional y tecnico del personal segun las necesidades pedagogicas y administrativas del establecimiento.'),
  (51, 'Gestion de recursos', 'Gestion de personal', '10.5', 'El sostenedor y el equipo directivo promueven un clima laboral positivo.'),
  (52, 'Gestion de recursos', 'Gestion de recursos financieros', '11.1', 'El sostenedor o el equipo directivo gestiona la matricula y la asistencia de los estudiantes.'),
  (53, 'Gestion de recursos', 'Gestion de recursos financieros', '11.2', 'El sostenedor asegura la sustentabilidad del Proyecto Educativo Institucional de los establecimientos a su cargo, rigiendose por un presupuesto, controlando los gastos y rindiendo cuenta del uso de los recursos.'),
  (54, 'Gestion de recursos', 'Gestion de recursos financieros', '11.3', 'El sostenedor y el equipo directivo se aseguran de cumplir con la normativa vigente.'),
  (55, 'Gestion de recursos', 'Gestion de recursos financieros', '11.4', 'El sostenedor y el equipo directivo conocen las redes, programas de apoyo y asistencia tecnica disponibles, y los usan para potenciar su Proyecto Educativo Institucional..'),
  (56, 'Gestion de recursos', 'Gestion de recursos educativos', '12.1', 'El sostenedor y el equipo directivo se aseguran de mantener la infraestructura y el equipamiento en buen estado para desarrollar la labor educativa'),
  (57, 'Gestion de recursos', 'Gestion de recursos educativos', '12.2', 'El sostenedor y el equipo directivo se aseguran de contar con los recursos didacticos y promueven su uso para potenciar el aprendizaje de los estudiantes.'),
  (58, 'Gestion de recursos', 'Gestion de recursos educativos', '12.3', 'El sostenedor y el equipo directivo se aseguran de contar con una biblioteca escolar CRA para apoyar el aprendizaje de los estudiantes y fomentar el habito lector.')
on conflict (id) do update
set
  dimension = excluded.dimension,
  sub_dimension = excluded.sub_dimension,
  numero_estandar = excluded.numero_estandar,
  descripcion_estandar = excluded.descripcion_estandar;

select setval(
  pg_get_serial_sequence('public.eid', 'id'),
  coalesce((select max(id) from public.eid), 1),
  true
);