export const PERMITTED_DIRECTOR_EMAILS = [
  "andrea.nunez@slepcolchagua.cl",
  "andres.san@slepcolchagua.cl",
  "cristian.fernandez@slepcolchagua.cl",
  "dorian.tobar@slepcolchagua.cl",
  "eduar.perez@slepcolchagua.cl",
  "eduardo.palma@slepcolchagua.cl",
  "fernando.maureira@slepcolchagua.cl",
  "gislenne.gaete@slepcolchagua.cl",
  "gladys.gatica@slepcolchagua.cl",
  "hugo.inostroza@slepcolchagua.cl",
  "irma.jara@slepcolchagua.cl",
  "ivonne.maldonado@slepcolchagua.cl",
  "josue.soto@slepcolchagua.cl",
  "juan.farias@slepcolchagua.cl",
  "luz.jara@slepcolchagua.cl",
  "manuel.guinez@slepcolchagua.cl",
  "marcela.gonzalezr@slepcolchagua.cl",
  "maria.mella@slepcolchagua.cl",
  "maria.moralesf@slepcolchagua.cl",
  "monica.becerram@slepcolchagua.cl",
  "nelly.villablanca@slepcolchagua.cl",
  "paola.galaz@slepcolchagua.cl",
  "regina.nieto@slepcolchagua.cl",
  "silvana.cordero@slepcolchagua.cl",
  "teresa.ramirez@slepcolchagua.cl",
] as const;

export const PERMITTED_DIRECTOR_EMAIL_SET = new Set(PERMITTED_DIRECTOR_EMAILS.map((email) => email.trim().toLowerCase()));